SRCS = OGTKDataProcessingNotImplementedException.m \
	OGTKGIRNoPackageException.m \
	OGTKIncorrectConfigException.m \
	OGTKNamespaceContainsNoClassesException.m \
	OGTKNoGIRAPIException.m \
	OGTKNoGIRDictException.m \
	OGTKReceivedNilExpectedStringException.m \
	OGTKClassNoTypeException.m

STATIC_LIB_NOINST = lib.a

include ../../buildsys.mk
